name: publish
on:
  release:
    types: [published]
jobs:
  test_minimal_app:
    # tests the hello-world example against a minimal install
    name: Test Minimal Application with Base Dependencies
    runs-on: ubuntu-latest
    env:
      python_version: "3.10"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install App Dependencies
        run: poetry install --no-interaction --no-root --only main
      - name: Install Test Dependencies
        run: poetry run python -m pip install pytest pytest-asyncio httpx cryptography
      - name: Set pythonpath
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      - name: Test
        run: poetry run pytest examples/tests/test_hello_world.py
